{% set name = "causal-learn" %}
{% set version = "0.1.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/causal-learn-{{ version }}.tar.gz
  sha256: f2206a883306d7ea4b7c15da82ed7cf837a1fefe72e59d507c6c70d27a13a644

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - scipy
    - scikit-learn
    - python-graphviz
    - statsmodels
    - pandas
    - matplotlib-base
    - networkx
    - pydot
    - tqdm

test:
  imports:
    - causallearn
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/py-why/causal-learn
  summary: causal-learn Python Package
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kunwuz
