{% set name = "causal-learn" %}
{% set version = "0.1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 134128f707fec11c698f732e89ad1d58154c8ebf8d8cc189f2a1c6dca4a68b31

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy
    - scipy
    - scikit-learn
    - python-graphviz
    - statsmodels
    - pandas
    - matplotlib-base
    - networkx
    - pydot
    - tqdm

test:
  imports:
    - causallearn
  commands:
    - pip install momentchi2
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/py-why/causal-learn
  summary: causal-learn Python Package
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kunwuz
