{% set name = "causal-learn" %}
{% set version = "0.1.3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/causal-learn-{{ version }}.tar.gz
  sha256: bf6517d1ad2e15094210dfef61a99623e05e1b758d6073aad9fcda2511625b39

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - numpy
    - scipy
    - scikit-learn
    - python-graphviz
    - statsmodels
    - pandas
    - matplotlib-base
    - networkx
    - pydot
    - tqdm

test:
  imports:
    - causallearn
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/py-why/causal-learn
  summary: causal-learn Python Package
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kunwuz
